server:
  port: 8090

sqs:
  url: https://sqs.us-east-1.amazonaws.com/002658803700/admissoes-dev
  port: 8090

bucket:
  name: auditoria-dasa
access:
  key: AKIAQBHT2D72K3K5BYR3
secret:
  key: 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

url-arquivo:
  marca: src/main/resources/static/marca
  unidade: src/main/resources/static/unidade
#  classes/static/marca

url:
  api:
    dasa:
      gliese:
        data: http://gliese-data.azr-dev.dasaexp.io
      marca: 1
      sistema: 14