spring:
  profiles: dev
server:
  port: 8090
  
queue:
  name: admissoes-dev
access:
  key: AKIAQBHT2D72K3K5BYR3
secret:
  key: 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

url-arquivo:
  marca: src/main/resources/static/marca
  unidade: src/main/resources/static/unidade
#  classes/static/marca